apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager
  - cnpg
  - kube-vip
  - longhorn
  - multus
  - oci-controller
  - oci-port-controller
  - powerdns
  - redis
  - traefik
