apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authentik
  - cinepro
  - headlamp
  - home-assistant
  - matrix
  - media
  - monitoring
  - mqtt
  - nextcloud
  - ntfy
  - obsidian
  - unifi
  - uptime-kuma
  - vaultwarden
  - vmd1-dev
