apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingressroute.yaml
  - dashboard.yaml
  - compress.yaml
  - security-headers.yaml
  - rate-limit.yaml
  - tls-option.yaml
  - lb-uk-home.yaml
