apiVersion: v1
kind: Service
metadata:
  name: traefik-uk-home-lb
  namespace: traefik
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.12.20"
spec:
  type: LoadBalancer
  loadBalancerClass: kube-vip.io/kube-vip-class
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
    - name: websecure
      port: 443
      targetPort: 443
      protocol: TCP
