apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: kube-system
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  targetNamespace: longhorn-system
  valuesContent: |-
    global:
      nodeSelector:
        storage.vmd1.homelab/longhorn-client: "true"
    csi:
      attacherReplicaCount: 2
      provisionerReplicaCount: 2
      resizerReplicaCount: 2
      snapshotterReplicaCount: 2
    defaultSettings:
      createDefaultDiskLabeledNodes: true
      systemManagedComponentsNodeSelector: "storage.vmd1.homelab/longhorn-client:true"
      storageNetwork: "longhorn-system/storage-macvlan-eth0"
      taintToleration: ""
      backupTarget: "s3://homelab-longhorn@eu-central-003/"
      backupTargetCredentialSecret: "longhorn-backup-secret"
---

