apiVersion: v1
kind: Namespace
metadata:
  name: mqtt

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-pvc
  namespace: mqtt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mqtt
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true

    listener 9001
    protocol websockets

    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mqtt
  labels:
    app: mosquitto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        topology.kubernetes.io/zone: uk-home
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.18
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: websocket
              containerPort: 9001
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: config-volume
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: data-volume
              mountPath: /mosquitto/data
      volumes:
        - name: config-volume
          configMap:
            name: mosquitto-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: mqtt-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mqtt
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.12.12"
  labels:
    app: mosquitto
spec:
  type: LoadBalancer
  loadBalancerClass: kube-vip.io/kube-vip-class
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
    - name: websocket
      port: 9001
      targetPort: 9001
      protocol: TCP
